### ISSUE TITLE
Nightly builds for Aries is 404 

### ISSUE THREAD

**Issue by dynamis** [silklabs/silk#16]
I've read your [post](http://nefzaoui.tn/2016/12/01/sony-xperia-z3c-silk/) and want to try your Silk OS on Aries (which is used for Firefox OS in the past) but it's unfortunately 404 now:

* https://github.com/silklabs/silk/blob/master/docs/downloads.md -> 
* https://d2xr8z98rg6hpy.cloudfront.net/nightly/aries/linux/1.9.0/target.tar.gz

**Comment by mvines** [comment]
Ack, thanks.  I'll take a look tomorrow.  Seems like the tip aries builds are red.  In the meantime you could try grabbing https://d2xr8z98rg6hpy.cloudfront.net/nightly/aries/linux/1.8.0/target.tar.gz

**Comment by mvines** [comment]
Fixed now, 1.9.0 no longer 404s.  Thanks for letting us know!
