### ISSUE TITLE
Build from source fails due to missing babel-core

### ISSUE THREAD

**Issue by chr1shaefn3r** [silklabs/silk#17]
I'm trying to build silk from source using the docker image silklabs/silk following the instructions [here](https://github.com/silklabs/silk/tree/master/docker) and [here](https://github.com/silklabs/silk/blob/master/docs/development/build-instructions-linux-osx.md).

Unfortunately make returns with:

```
make[1]: Leaving directory `/home/silk/silk/bsp-gonk/external/node'

#### make failed to build some targets (07:05 (mm:ss)) ####
```

I hopped the failed targets might be optional and not needed, but trying to flash the result using "flash all" tells me he can't find the image.

I uploaded the complete logoutput from "make" [here](https://owncloud.christophhaefner.de/s/gOijLqGz8Hj88Uh).
It contains many of the following lines: `ERROR in Cannot find module 'babel-core'` hence the title.

> What operating system, OS version, and processor architecture are you using?

Docker image from [https://hub.docker.com/r/silklabs/silk/](https://hub.docker.com/r/silklabs/silk/)

> What did you do?

Follow the [build-instructions](https://github.com/silklabs/silk/blob/master/docs/development/build-instructions-linux-osx.md) till "flash all"

> What did you expect to see?

Successfully flashing of the silk image onto my Nexus 5

> What did you see instead?

An error by fastboot that he couldn't find the image. Maybe it is not a 'babel-core not found issue', but a directory issue. Could someone please clarify from which directory `fastboot flash all` should be started?

Thanks for your suppport. Looking forward to working with your platform.

**Comment by raj2sudha1** [comment]
same issue with me.
OS : linux
used these commands : 
$ ./sync hammerhead
$ source build/envsetup.sh
$ make -j4

Error:#### make failed to build some targets (05:10 (mm:ss)) ####

**Comment by mvines** [comment]
@chr1shaefn3r, sorry for taking so long to get back to you.  This should now be fixed by:
05fd328 - Add silk-core-version symlink
4710680 - Add missing packages 
9bee085 - Update node_modules 

@raj2sudha1 -- same for the issue you reported.

Thanks guys for the reports.  I've filed #19 as a follow-up because this really could have been caught much earlier in theory.

If you're still having trouble please re-open this issue or file something new.

**Comment by chr1shaefn3r** [comment]
Looks good to me:

`#### make completed successfully (28:03 (mm:ss)) ####`

Thank you very much :)
