### ISSUE TITLE
Build failed for Nexus 5 - hammerhead

### ISSUE THREAD

**Issue by raj2sudha1** [silklabs/silk#18]
Build failed:
    Cannot find module 'silk-core-version'
    Cannot find module 'look-up'

Commands used for build:
./sync hammerhead
source build/envsetup.sh
make -j4

**Comment by mvines** [comment]
Should be fixed now.  Please see https://github.com/silklabs/silk/issues/17#issuecomment-281900879 for details

**Comment by raj2sudha1** [comment]
Thank you!.  Will try again and let you know.

**Comment by raj2sudha1** [comment]
CMake Error at 3rdparty/tbb/CMakeLists.txt:91 (message):
  **Failed to download TBB sources** (1;"Unsupported protocol"):
  http://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20160128oss_src_0.tgz

Could you please check this out.

**Comment by jainanshul** [comment]
What is the output of `cmake --version`? Please upgrade to `cmake 3.5.2` or later as some older versions of cmake don't support OpenSSL required to download some `opencv` libraries.
