### ISSUE TITLE
sourcing envsetup.sh crashes shell (iterm2)

### ISSUE THREAD

**Issue by paulwalker** [silklabs/silk#2]
on osx 10.11.5 (latest), xcode & other pre-requisites satisfied

**Comment by mvines** [comment]
Normal OS X Terminal works for you though?

**Comment by mvines** [comment]
I honestly don't see how this could be something we're doing.  Maybe iterm2 has a bug.  If there's more info that can be provided, please LMK.  Otherwise there's not much to do here.

**Comment by paulwalker** [comment]
it's probably some sort of tty issue, etc...are you not developing on osx?

**Comment by mvines** [comment]
Most of the team are on OS X.  We fully support both OS X and Linux.  I made several builds on my MBP earlier this evening.  Any idea where it's crashing for you within envsetup.sh?  Same thing happens with Terminal or is the crash iterm2 specific?
