### ISSUE TITLE
Build failed for Nexus 5 - hammerhead - CMake

### ISSUE THREAD

**Issue by raj2sudha1** [silklabs/silk#20]
CMake Error at 3rdparty/tbb/CMakeLists.txt:91 (message):
  **Failed to download TBB sources** (1;"Unsupported protocol"):
  http://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20160128oss_src_0.tgz

Could you please check this out.

**Comment by raj2sudha1** [comment]
that tbb path is "Moved permanently"

**Comment by mvines** [comment]
Hmm...I can't reproduce this issue here.

http://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20160128oss_src_0.tgz does 301, however the redirect works.  As a test, can you fetch the file with this command right?
```sh
$ curl -L -o tbb44_20160128oss_src_0.tgz \
    http://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20160128oss_src_0.tgz     
```
That download runs within `cmake`, and is unmodified from upstream OpenCV.  What's your cmake version?  I'm running:
```
$ cmake --version
cmake version 3.3.2
```

A console log from running the following commands might help debug too:
```
$ cd bsp-gonk/
$ source build/envsetup.sh
$ cd external/opencv3
$ mm
```

**Comment by raj2sudha1** [comment]
cmake version is 3.5.2

**Comment by jainanshul** [comment]
@raj2sudha1 Seems like I just asked you a question on the other issue you filed for the information above. Seems like you are using the correct cmake version. Wondering if you could re-install cmake from https://cmake.org/files/v3.5/ and please try again.

**Comment by raj2sudha1** [comment]
i tried the steps provided here. Still i am getting the above mentioned error.
So, i manually downloaded the tbb file and moved to respective folder. the problem solved for the tbb file.

But not facing another issue.
-- Downloading v3.1.0/protobuf-cpp-3.1.0.tar.gz...
CMake Error at /home/raj/learning/silk/bsp-gonk/external/opencv3/cmake/OpenCVUtils.cmake:1043 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/raj/learning/silk/bsp-gonk/external/opencv3_contrib/modules/dnn/.download/bd5e3eed635a8d32e2b99658633815ef/v3.1.0/protobuf-cpp-3.1.0.tar.gz]
      expected hash: [bd5e3eed635a8d32e2b99658633815ef]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [1;"Unsupported protocol"]

Call Stack (most recent call first):

**Comment by mvines** [comment]
A hash mismatch like that generally indicates something strange with your network, as you didn't get the right bits for some reason.

Coincidentally,I just made a change that  should alleviate the need to download that file though. :)
See 4960ff8d65b701997b7c3b6a4d41f12fa0aedc00 for more

**Comment by raj2sudha1** [comment]
Thank you! for helping me to resolve the issue.
#### make completed successfully (26:50 (mm:ss)) ####
