### ISSUE TITLE
Uninstall Silk on Redmi Note 3 Pro

### ISSUE THREAD

**Issue by jakewilkins** [silklabs/silk#23]
Hey, I know this isn't a Silk issue but I can't for the life of me figure out how to flash any other Android on to the development Note 3 that I got in the developer bundle.

I see [here](https://github.com/silklabs/silk/blob/9eb2edac5855fa6f7c4bb59def12b31df0d69f65/docs/development/build-instructions-linux-osx.md) how to do it for a Nexus, but that process fails with the Redmi Note 3.

Can you point me in the right direction? Everything I find wants you to load something on an SD card and then update using the OS.

Any help is hugely appreciated.

**Comment by mvines** [comment]
We do have a AOSP kenzo build in the tree, the board manifest is at https://github.com/silklabs/silk/tree/master/bsp-gonk/board/aospkenzo

If you sync/build/flash this board on your kenzo, it'll give you (very close to) stock AOSP.

Roughly:
```
$ cd bsp-gonk/
$ ./sync aospkenzo
$ souce build/envsetup.sh
$ make -j$(nproc)
$ adb reboot-bootloader
$ fastboot flash all
```
