### ISSUE TITLE
Allow node > 6 support

### ISSUE THREAD

**Issue by aaronjheinen** [silklabs/silk#24]
The npm package has a `postinstall` script to make sure the node version is 6 and the npm version is 3, my local install fails because my node verson is 8.0.0

Is there a reason these are limited to exactly 6 and 3 and not greater than 6 and 3?

**Comment by mvines** [comment]
Yes we do that intentionally to ensure everybody has the same environment.   We prefer to live on node LTS, so we'll jump to node 8 once it becomes LTS in October.

But you could use a tool like [nvm](https://github.com/creationix/nvm) to manage the node version we require along side node 8.0.0.

Thanks for the report, I'm going to close this issue though as it's per design

**Comment by aaronjheinen** [comment]
Cheers, thanks for the explanation.
