### ISSUE TITLE
Release babel-plugin-rewrite-require 1.13

### ISSUE THREAD

**Issue by mikelambert** [silklabs/silk#25]
The latest version on npm is 1.9.1, and I am interested in using `throwForModules` functionality (committed four months ago, but which has not been released yet).

And since this is a nested package, it makes it impossible to install with the `npm install github:...` approach in the meantime.

**Comment by mvines** [comment]
Fixed! 1.13.0 is now published at https://www.npmjs.com/package/babel-plugin-rewrite-require
