### ISSUE TITLE
provide a Dockerfile for development

### ISSUE THREAD

**Issue by paulwalker** [silklabs/silk#3]

**Comment by mvines** [comment]
Yeah that'd be nice for sure.  We have the build requirements documented so this shouldn't be hard to do

**Comment by borromeotlhs** [comment]
I meant to get on this and it completely fell off my radar.  I'll see what I can do. . .

**Comment by borromeotlhs** [comment]
https://github.com/borromeotlhs/docker-silk is the rough draft I'm still debugging.  I'll have to see if this needs updating wrt the specific ubuntu version, gcc, etc. . .  I'll then have to figure out if the install still hangs on openjdk server CA certs (https://github.com/docker/docker/issues/18180).  I distinctly remember that this prevented me from finishing the dockerfile in September.  I think upgrading the kernel to 3.13.0-79.123 or later should work. . .

**Comment by borromeotlhs** [comment]
OK, I unfortunately don't have a great or reliable windows docker setup such that I can't finish pushing the image to dockerhub.  In lieu of that, https://github.com/borromeotlhs/docker-silk now have a v0.1 of a silk dev environment.

@paulwalker : does this work for you?

**Comment by borromeotlhs** [comment]
https://github.com/silklabs/silk/pull/13

**Comment by mvines** [comment]
Fixed by #13
