### ISSUE TITLE
[Emulator] 403 error when running npm install

### ISSUE THREAD

**Issue by KevinGrandon** [silklabs/silk#5]
I was poking around and trying to install the emulator. I ran into a 403 error when trying to access this URL: https://d2xr8z98rg6hpy.cloudfront.net/nightly/qemu/darwin/master/0.17.0/target.tar.gz

https://github.com/silklabs/silk/blob/master/sdk-emulator/bin/postinstall#L7-L8

**Comment by mvines** [comment]
Ugh, I know I know.   We're building the OS X emulator on Travis and having trouble getting it under the build timeout.   I've been poking at it for a little while now trying to trim some more fat.  I'll update here once we get that fixed.

**Comment by mvines** [comment]
Should be fixed with [silk-emulator@0.18.0](https://www.npmjs.com/package/silk-emulator).  Thanks for the 👢 to get me to finally fix this (longstanding OS X) issue!

FTR:
* 3132fc6f52ed2d5c700a4303b902176c253de4d4
* 2fabce439e2c3f84894d56b944c5b78ae9ffc54e
